function [synthetic_tform,g_s_m_i1,error_msg] = add_synthetic_joint_tf_for_ga(synthetic_name,g_s_m_i,assembly_parameters,assembly_index)
% Based on add_synthetic_joint_tf.m BUT modified to accept optimization
% assembly parameters for each different assembly generated by the ga. The
% assembly_index specifies which parameters should be set to calculate
% synthetic_tf

% -------> OPTIMIZATION ASSEMBLY PARAMETERS ARE NOW GIVEN FROM GA!  <-------
synthetic_origin_xzp = assembly_parameters(assembly_index,:);

active2pseudo_origin_p = assembly_parameters(4,assembly_index);
% ==================================================

switch synthetic_name
    case 'synthetic1'   % base_link->pseudo_static_under
        syn1_rpy = [0 0 0];
        syn1_xyz = [0 0 0.048]';

        synthetic_tform = eul2tform(syn1_rpy);
        synthetic_tform(1:3,4) = syn1_xyz;

        % New global tf
        g_s_m_i1 = g_s_m_i * synthetic_tform;
        error_msg = false;

    case 'synthetic2'   % pseudo_moving->pseudo_static_under
        syn2_rpy = [0 synthetic_origin_xzp(3) 0];
        syn2_xyz = [synthetic_origin_xzp(1) 0.1444 synthetic_origin_xzp(2)]';

        synthetic_Rot_tf = rotz(syn2_rpy(3))*roty(syn2_rpy(2))*rotx(syn2_rpy(1));
        [wmega_Rsyn, theta_Rsyn] = rotparam(synthetic_Rot_tf);
        exp_wmega_Rsyn = skewexp(wmega_Rsyn, theta_Rsyn);
        
        synthetic_tform = [exp_wmega_Rsyn syn2_xyz; 0 0 0 1];   % the local tf induced by synthetic joint
        
        % New global tf
        g_s_m_i1 = g_s_m_i * synthetic_tform;
        error_msg = false;
        
    case 'synthetic3'   % pseudo_moving->pseudo_static_under
        syn3_rpy = [0 synthetic_origin_xzp(3) 0];
        syn3_xyz = [synthetic_origin_xzp(1) 0.0955 synthetic_origin_xzp(2)]';

        synthetic_Rot_tf = rotz(syn3_rpy(3))*roty(syn3_rpy(2))*rotx(syn3_rpy(1));
        [wmega_Rsyn, theta_Rsyn] = rotparam(synthetic_Rot_tf);
        exp_wmega_Rsyn = skewexp(wmega_Rsyn, theta_Rsyn);
        
        synthetic_tform = [exp_wmega_Rsyn syn3_xyz; 0 0 0 1];   % the local tf induced by synthetic joint
        
        % New global tf
        g_s_m_i1 = g_s_m_i * synthetic_tform;
        error_msg = false;        
    case 'synthetic4'   % pseudo_moving->pseudo_static_under
        syn4_rpy = [-1.5708 synthetic_origin_xzp(3) 0];
        syn4_xyz = [synthetic_origin_xzp(1) 0.101 synthetic_origin_xzp(2)]';

%         synthetic_tform = eul2tform(syn4_rpy);
%         synthetic_tform(1:3,4) = syn4_xyz;
        synthetic_Rot_tf = rotz(syn4_rpy(3))*roty(syn4_rpy(2))*rotx(syn4_rpy(1));
        [wmega_Rsyn, theta_Rsyn] = rotparam(synthetic_Rot_tf);
        exp_wmega_Rsyn = skewexp(wmega_Rsyn, theta_Rsyn);
        
        synthetic_tform = [exp_wmega_Rsyn syn4_xyz; 0 0 0 1];   % the local tf induced by synthetic joint
        
        % New global tf
        g_s_m_i1 = g_s_m_i * synthetic_tform;
        error_msg = false;
    case 'synthetic5'   % pseudo_moving->pseudo_static_under
        syn5_rpy = [-1.5708 synthetic_origin_xzp(3) 0];
        syn5_xyz = [ synthetic_origin_xzp(1) 0.0525 synthetic_origin_xzp(2)]';

        synthetic_Rot_tf = rotz(syn5_rpy(3))*roty(syn5_rpy(2))*rotx(syn5_rpy(1));
        [wmega_Rsyn, theta_Rsyn] = rotparam(synthetic_Rot_tf);
        exp_wmega_Rsyn = skewexp(wmega_Rsyn, theta_Rsyn);
        
        synthetic_tform = [exp_wmega_Rsyn syn5_xyz; 0 0 0 1];   % the local tf induced by synthetic joint
        
        % New global tf
        g_s_m_i1 = g_s_m_i * synthetic_tform;
        error_msg = false;        
    case 'active_assembly'
        active2pseudo_origin_rpy= [0 active2pseudo_origin_p 0];
        active2pseudo_origin_xyz= [0 0.1 0]'; 
                
        active2pseudo_Rot_tf = rotz(active2pseudo_origin_rpy(3))*roty(active2pseudo_origin_rpy(2))*rotx(active2pseudo_origin_rpy(1));
        [wmega_Ractive2pseudo, theta_Ractive2pseudo] = rotparam(active2pseudo_Rot_tf);
        exp_wmega_Ractive2pseudo = skewexp(wmega_Ractive2pseudo, theta_Ractive2pseudo);
        
        synthetic_tform = [exp_wmega_Ractive2pseudo active2pseudo_origin_xyz; 0 0 0 1];   % the local tf induced by active2pseudo assembly
        
        % New global tf
        g_s_m_i1 = g_s_m_i * synthetic_tform;
        error_msg = false;

    otherwise
        error_msg = true;
end

end